### ISSUE TITLE
[FEATURE] Connect with http_interceptor: library

### ISSUE THREAD

**Issue by II11II** [jhomlala/alice#85]
There is a popular interceptor for  http library [https://github.com/CodingAleCR/http_interceptor](https://github.com/CodingAleCR/http_interceptor)
Please add a feature to intercept requests with http_interceptor library.

P.s. I've seen an example and it violates SOLID principles (No DI for http library)

**Comment by jhomlala** [comment]
@II11II http_interceptor is an interceptor for Dart's http library which is supported in Alice. Why should I add support for library which simply intercepts requests/responses rather than sending it? Alice provides support for libraries which are http clients. 

`P.s. I've seen an example and it violates SOLID principles (No DI for http library)`
This is example app which shows how to use Alice in the easiest way. There's no purpose of architecting example app with SOLID principles since it's only showcase of features.

**Comment by II11II** [comment]
@jhomlala 
In example i should refactor my each remotedatasource while adding method of alice.
Are there easier way to do it?

**Comment by II11II** [comment]
> @II11II http_interceptor is only an interceptor for Dart's http library which is supported in Alice. Why should I add support for library which simply intercepts requests/responses rather than sending it? Alice provides support for libraries which are http clients.
> 
> `P.s. I've seen an example and it violates SOLID principles (No DI for http library)`
> This is example app which shows how to use Alice in the easiest way. There's no purpose of architecting example app with SOLID principles since it's only showcase of features.

Can you add a method  ```onHttpClientRequest(BaseRequest request,{dynamic body})``` ?
BaseRequest is class in HTTP library.

And give please access to fill your ```AliceHttpRequest``` class creating method in the Alice class

**Comment by jhomlala** [comment]
@II11II I'm sorry but I don't understand your request. Can you elaborate it?
